name: build docs

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    
jobs:
  lets-do-this:
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Build
      run: |
        yarn install
        echo it is done
    
   
    
